# version: '3.8'

# services:
#   rtsp-stream:
#     image: agnes091043/babe-iot:ws-camera
#     container_name: rtsp-stream-container
#     platform: linux/amd64
#     ports:
#       - "9999:9999"
#     environment:
#       - NODE_ENV=production
#     restart: always

#   web:

version: '3.8'

services:
  rtsp-stream:
    image: agnes091043/babe-iot:ws-camera
    container_name: rtsp-stream-container
    platform: linux/amd64
    ports:
      - "9999:9999"  # WebSocket port
      - "8093:8093"  # API port
    environment:
      - NODE_ENV=production
      - RTSP_URL=
      - WS_PORT=9999
      - PORT=8093
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    working_dir: /app
    command: ["node", "server.js"]
    restart: always
